
[package]
name = "client"
version = "0.1.0"
edition = "2021"  # Corrigido de 2024 para 2021

[dependencies]
mcprs = { path = "../../" }
serde_json = "1.0"
reqwest = "0.11"                               # Adicionado
tokio = { version = "1", features = ["full"] } # Adicionado
